### ISSUE TITLE
Dot in github repository name crashes elm-test

### ISSUE THREAD

**Issue by antivanov** [rtfeldman/node-test-runner#165]
When there is a dot in the repository name elm-test crashes with a cryptic error. Reproducible with the repository https://github.com/antivanov/underscore.elm

```
$ elm-test
Unhandled exception while running the tests: TypeError: Cannot read property '1' of null
    at Object.repositoryToNativePackageName (/home/anton/Apps/node-v6.11.0-linux-x64/lib/node_modules/elm-test/lib/runner.js:55:12)
    at generatePackageJson (/home/anton/Apps/node-v6.11.0-linux-x64/lib/node_modules/elm-test/bin/elm-test:408:12)
    at runElmTest (/home/anton/Apps/node-v6.11.0-linux-x64/lib/node_modules/elm-test/bin/elm-test:279:22)
    at Object.<anonymous> (/home/anton/Apps/node-v6.11.0-linux-x64/lib/node_modules/elm-test/bin/elm-test:562:1)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.runMain (module.js:604:10)
```

Looking into the source code or runner.js I found that the following regex is used to parse the repository name:

```js
  var matches = repository.match(/\/([^\/]+)\/([^\/\.]+)\.git/);
```

Looks like the regex should be modified and the last dot exclusion removed. Then the new regex will match all the previous package names and also the ones that include dots in them. I will create a PR.

**Comment by zwilias** [comment]
If I'm not mistaken, elm-lang/elm-make#106 basically means you could get runtime errors because of this. Perhaps instead of allowing it, we should display a better error message?

**Comment by antivanov** [comment]
Yes, @zwilias, good point. Actually allowing dot in the repository name at this point just leads to the elm-make failing later. At least we should then provide a better error message, I will update the pull request. Dots will not be allowed still, but this will be communicated clearer.
