### ISSUE TITLE
--watch crashes on Windows 10

### ISSUE THREAD

**Issue by edmellum** [rtfeldman/node-test-runner#255]
I've replicated on two separate Windows 10 machines that `--watch` causes a crash with the following stack trace after a file is changed:

```
Unhandled exception while running the tests: { Error: EINVAL: invalid argument, unlink '\\.\pipe\elm_test-9172'
    at Object.fs.unlinkSync (fs.js:1061:18)
    at Function.rimrafSync [as sync] (C:\Users\104171damu\AppData\Roaming\npm\node_modules\elm-test\node_modules\rimraf\rimraf.js:306:17)
    at Object.removeSync (C:\Users\104171damu\AppData\Roaming\npm\node_modules\elm-test\node_modules\fs-extra\lib\remove\index.js:4:17)
    at Object.run (C:\Users\104171damu\AppData\Roaming\npm\node_modules\elm-test\lib\supervisor.js:249:6)
    at ChildProcess.<anonymous> (C:\Users\104171damu\AppData\Roaming\npm\node_modules\elm-test\lib\elm-test.js:212:18)
    at emitTwo (events.js:126:13)
    at ChildProcess.emit (events.js:214:7)
    at ChildProcess.cp.emit (C:\Users\104171damu\AppData\Roaming\npm\node_modules\elm-test\node_modules\cross-spawn\lib\enoent.js:40:29)
    at maybeClose (internal/child_process.js:925:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
  errno: -4071,
  code: 'EINVAL',
  syscall: 'unlink',
  path: '\\\\.\\pipe\\elm_test-9172' }
```

I tried running it on several different versions of node-test-runner and found 0.18.12 to be the version where this first started happening. 0.18.11 seems to have a different crash that happens right away. 0.18.10 seems to work OK.

**Comment by theghostbel** [comment]
Downgrading to 0.18.9 helped, thanks!

**Comment by HappMacDonald** [comment]
What's in the changelog since 0.18.9? (I can't find a changelog..)

**Comment by rtfeldman** [comment]
Just pushed a potential fix - let me know if this works!

```
$ npm remove --global elm-test
$ npm install --global elm-test@0.18.13-beta2
```

**Comment by HappMacDonald** [comment]
Still crashing in 0.18.13-beta2, but different crash now:

```
C:\cygwin64\home\jesse\unison\dev\elm-modules>elm-test --watch
Success! Compiled 70 modules.
Successfully generated /dev/null
Running in watch mode
Success! Compiled 16 modules.
Successfully generated C:\cygwin64\home\jesse\unison\dev\elm-modules\elm-stuff\generated-code\elm-community\elm-test\elmTestOutput.js

elm-test 0.18.13-beta2
----------------------

Running 22 tests. To reproduce these results, run: elm-test --fuzz 100 --seed 475654549


TEST RUN PASSED

Duration: 638 ms
Passed:   22
Failed:   0

Watching for changes...

MyBasicsTest.elm changed. Rebuilding!
Success! Compiled 1 module.
Successfully generated C:\cygwin64\home\jesse\unison\dev\elm-modules\elm-stuff\generated-code\elm-community\elm-test\elmTestOutput.js
Unhandled exception while running the tests: { Error: EINVAL: invalid argument, unlink '\\.\pipe\elm_test-12504'
    at Object.fs.unlinkSync (fs.js:1061:18)
    at Function.rimrafSync [as sync] (C:\Users\jesse\AppData\Roaming\npm\node_modules\elm-test\node_modules\rimraf\rimraf.js:306:17)
    at Object.removeSync (C:\Users\jesse\AppData\Roaming\npm\node_modules\elm-test\node_modules\fs-extra\lib\remove\index.js:4:17)
    at Object.run (C:\Users\jesse\AppData\Roaming\npm\node_modules\elm-test\lib\supervisor.js:250:8)
    at ChildProcess.<anonymous> (C:\Users\jesse\AppData\Roaming\npm\node_modules\elm-test\lib\elm-test.js:212:18)
    at emitTwo (events.js:126:13)
    at ChildProcess.emit (events.js:214:7)
    at ChildProcess.cp.emit (C:\Users\jesse\AppData\Roaming\npm\node_modules\elm-test\node_modules\cross-spawn\lib\enoent.js:40:29)
    at maybeClose (internal/child_process.js:925:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
  errno: -4071,
  code: 'EINVAL',
  syscall: 'unlink',
  path: '\\\\.\\pipe\\elm_test-12504' }
```
