### ISSUE TITLE
npm install error: Cannot find module 'request'

### ISSUE THREAD

**Issue by n1k0** [rtfeldman/node-test-runner#266]
I'm trying to install the beta version of elm-test for 0.19, but I'm encountering errors:

```
$ npm i elm-test@beta --save-dev

> elmi-to-json@0.19.0-rc3 install /home/niko/work/allomedia/canopy/node_modules/elmi-to-json
> binwrap-install


###
### The "request" library is not installed automatically anymore.
### But required by "request-promise".
###
### npm install request --save
###

/home/niko/work/allomedia/canopy/node_modules/request-promise/lib/rp.js:23
    throw err;
    ^

Error: Cannot find module 'request'
    at Function.Module._resolveFilename (module.js:538:15)
    at Function.Module._load (module.js:468:25)
    at Module.require (module.js:587:17)
    at require (internal/module.js:11:18)
    at /home/niko/work/allomedia/canopy/node_modules/request-promise/lib/rp.js:11:16
    at module.exports (/home/niko/work/allomedia/canopy/node_modules/stealthy-require/lib/index.js:62:23)
    at Object.<anonymous> (/home/niko/work/allomedia/canopy/node_modules/request-promise/lib/rp.js:10:19)
    at Module._compile (module.js:643:30)
    at Object.Module._extensions..js (module.js:654:10)
    at Module.load (module.js:556:32)
    at tryModuleLoad (module.js:499:12)
    at Function.Module._load (module.js:491:3)
    at Module.require (module.js:587:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/home/niko/work/allomedia/canopy/node_modules/elmi-to-json/node_modules/binwrap/test.js:1:77)
    at Module._compile (module.js:643:30)
    at Object.Module._extensions..js (module.js:654:10)
    at Module.load (module.js:556:32)
    at tryModuleLoad (module.js:499:12)
    at Function.Module._load (module.js:491:3)
    at Module.require (module.js:587:17)
    at require (internal/module.js:11:18)
npm WARN request-promise@4.2.2 requires a peer of request@^2.34 but none is installed. You must install peer dependencies yourself.
npm WARN request-promise-core@1.1.1 requires a peer of request@^2.34 but none is installed. You must install peer dependencies yourself.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.1.2 (node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.1.2: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! elmi-to-json@0.19.0-rc3 install: `binwrap-install`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the elmi-to-json@0.19.0-rc3 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/niko/.npm/_logs/2018-08-23T12_33_53_616Z-debug.log
```

I'm using latest Ubuntu 18.04.1 and:

```
$ node --version
v8.9.4
$ npm --version
6.4.0
```

As suggested in the error message, running `npm i request --save-dev` solves the issue, though maybe this dependency should be added to the package dependencies?

**Comment by zwilias** [comment]
@n1k0 I think this was fixed through updates of the binwrap dependency. Do you still encounter this behaviour?

**Comment by n1k0** [comment]
@zwilias well there's no `@beta` npm dist-tag anymore :) I never encountered this issue again since I've first reported it here, I think it's safe to close this issue.
