### ISSUE TITLE
0.19 beta crashes on Windows 10

### ISSUE THREAD

**Issue by Y0hy0h** [rtfeldman/node-test-runner#275]
I'm having the [same issue as was present for 0.18](https://github.com/rtfeldman/node-test-runner/issues/255) with the beta for 0.19.

When I hit save in my editor (happens in both Atom and VSCode, on two different machines), the watch will output the following log:
```
[successful test run omitted]

Watching for changes...

..\src\Code.elm changed. Rebuilding!
Success! Compiled 3 modules.
Unhandled exception while running the tests: { Error: EINVAL: invalid argument, unlink '\\.\pipe\elm_test-12400'
    at Object.fs.unlinkSync (fs.js:1061:18)
    at Function.rimrafSync [as sync] (C:\Users\Y0hy0h\AppData\Local\Yarn\Data\global\node_modules\rimraf\rimraf.js:306:17)
    at Object.removeSync (C:\Users\Y0hy0h\AppData\Local\Yarn\Data\global\node_modules\fs-extra\lib\remove\index.js:4:17)
    at Object.run (C:\Users\Y0hy0h\AppData\Local\Yarn\Data\global\node_modules\elm-test\lib\supervisor.js:250:8)
    at ChildProcess.<anonymous> (C:\Users\Y0hy0h\AppData\Local\Yarn\Data\global\node_modules\elm-test\lib\elm-test.js:204:18)
    at emitTwo (events.js:126:13)
    at ChildProcess.emit (events.js:214:7)
    at ChildProcess.cp.emit (C:\Users\Y0hy0h\AppData\Local\Yarn\Data\global\node_modules\cross-spawn\lib\enoent.js:40:29)
    at maybeClose (internal/child_process.js:925:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
  errno: -4071,
  code: 'EINVAL',
  syscall: 'unlink',
  path: '\\\\.\\pipe\\elm_test-12400' }
```

6f53961077b6b29793d3b3a0198f96617bfe6a37 is supposed to fix the issue, but I have installed `elm-test@0.19.0-beta5` and it is still happening.

**Comment by Y0hy0h** [comment]
I just noticed that some of my local files have different line numberings. So the `elm-test.js:204:18` corresponds to [line 209](https://github.com/rtfeldman/node-test-runner/blob/0.19/lib/elm-test.js#L209). The line in `supervisor.js` is the [correct one](https://github.com/rtfeldman/node-test-runner/blob/0.19/lib/supervisor.js#L250).

**Comment by Y0hy0h** [comment]
I almost forgot that I have configured `elm-format` to run on save in every case! I will test if that is causing the issue.

**Comment by rtfeldman** [comment]
@Y0hy0h Can you try with the latest beta? I've pushed another attempted fix. 😛

**Comment by Y0hy0h** [comment]
I'm getting a different error now:
```
Error: listen EADDRINUSE \\.\pipe\elm_test-5776
    at Object._errnoException (util.js:1022:11)
    at _exceptionWithHostPort (util.js:1044:20)
    at Server.setupListenHandle [as _listen2] (net.js:1350:19)
    at listenInCluster (net.js:1408:12)
    at Server.listen (net.js:1503:5)
    at Object.run (C:\Users\Y0hy0h\AppData\Local\Yarn\Data\global\node_modules\elm-test\lib\supervisor.js:255:10)
    at ChildProcess.<anonymous> (C:\Users\Y0hy0h\AppData\Local\Yarn\Data\global\node_modules\elm-test\lib\elm-test.js:180:18)
    at emitTwo (events.js:126:13)
    at ChildProcess.emit (events.js:214:7)
    at ChildProcess.cp.emit (C:\Users\Y0hy0h\AppData\Local\Yarn\Data\global\node_modules\cross-spawn\lib\enoent.js:40:29)
    at maybeClose (internal/child_process.js:925:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
Unhandled exception while running the tests: { Error: write EPIPE
    at _errnoException (util.js:1022:11)
    at Socket._writeGeneric (net.js:780:25)
    at Socket._write (net.js:799:8)
    at doWrite (_stream_writable.js:397:12)
    at writeOrBuffer (_stream_writable.js:383:5)
    at Socket.Writable.write (_stream_writable.js:290:11)
    at Socket.write (net.js:717:40)
    at Server.initWorker (C:\Users\Y0hy0h\AppData\Local\Yarn\Data\global\node_modules\elm-test\lib\supervisor.js:201:12)
    at emitOne (events.js:116:13)
    at Server.emit (events.js:211:7)
    at Pipe.onconnection (net.js:1577:8) code: 'EPIPE', errno: 'EPIPE', syscall: 'write' }
```

Again, it seems to happen even without autosave in VSCode.

**Comment by Y0hy0h** [comment]
I've just tried out `0.19.0-beta10` and I noticed something interesting. When there are compilation errors, the watch works just fine. It's only when it actually runs the tests that I get the [error from above](https://github.com/rtfeldman/node-test-runner/issues/275#issuecomment-418756561).

**Comment by rtfeldman** [comment]
@Y0hy0h if you have the chance, can you try out the build in this PR? https://github.com/rtfeldman/node-test-runner/pull/309
