### ISSUE TITLE
`elm-test init` ignores `--compiler` flag

### ISSUE THREAD

**Issue by lpil** [rtfeldman/node-test-runner#292]
I always install Elm locally in my projects and run it from `./node_modules/.bin`.  For this to work with `elm-test` I use the `--compiler` flag, though it seems this doesn't work with the `elm-test init` command.

```
$ ./node_modules/.bin/elm-test init --compiler ./node_modules/.bin/elm
/bin/sh: 1: elm: not found
Unable to create temporary directory for elm-test install. { Error: Command failed: elm install elm-explorations/test
    at checkExecSyncError (child_process.js:603:11)
    at Object.execSync (child_process.js:640:13)
    at Object.install (/home/louis/src/waive/assets/node_modules/elm-test/lib/install.js:54:19)
    at Object.<anonymous> (/home/louis/src/waive/assets/node_modules/elm-test/lib/elm-test.js:160:11)
    at Module._compile (internal/modules/cjs/loader.js:702:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:713:10)
    at Module.load (internal/modules/cjs/loader.js:612:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:551:12)
    at Function.Module._load (internal/modules/cjs/loader.js:543:3)
    at Module.require (internal/modules/cjs/loader.js:650:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.<anonymous> (/home/louis/src/waive/assets/node_modules/elm-test/bin/elm-test:3:1)
    at Module._compile (internal/modules/cjs/loader.js:702:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:713:10)
    at Module.load (internal/modules/cjs/loader.js:612:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:551:12)
    at Function.Module._load (internal/modules/cjs/loader.js:543:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:744:10)
    at startup (internal/bootstrap/node.js:238:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:572:3)
  status: 127,
  signal: null,
  output: [ null, null, null ],
  pid: 6077,
  stdout: null,
  stderr: null }
```

What's the recommended method for using `elm-test init` without globally install Elm?

**Comment by rtfeldman** [comment]
This is a bug; `elm-test init` should respect `--compiler`.

Updated the title to reflect this!

**Comment by rtfeldman** [comment]
@lpil I think this is now fixed - can you try the current `elm-test@beta` and see if it reproduces for you?

**Comment by lpil** [comment]
Seems to work! :)

**Comment by rtfeldman** [comment]
Excellent! 😃

**Comment by lpil** [comment]
Thank you!
