### ISSUE TITLE
Give an understandable error message if nodejs is too old

### ISSUE THREAD

**Issue by avh4** [rtfeldman/node-test-runner#31]
See #29: the user had nodejs-0.10.25, which gives the following error:

```
$ elm-test init
elm-package.json already exists

/usr/local/lib/node_modules/elm-test/bin/elm-test:41
childProcess.execSync(elm["elm-package"] + " " + command + elmOptions, {
^
TypeError: Object # has no method 'execSync'
at execElmPackageSync (/usr/local/lib/node_modules/elm-test/bin/elm-test:41:20)
at Object. (/usr/local/lib/node_modules/elm-test/bin/elm-test:45:3)
at Module._compile (module.js:456:26)
at Object.Module._extensions..js (module.js:474:10)
at Module.load (module.js:356:32)
at Function.Module._load (module.js:312:12)
at Function.Module.runMain (module.js:497:10)
at startup (node.js:119:16)
at node.js:902:3
```

We should detect an old version of nodejs and give an error suggesting an upgrade.  (0.11+ is required for execSync).

**Comment by avh4** [comment]
See http://stackoverflow.com/questions/11707698/how-to-know-which-javascript-version-in-my-nodejs for how to detect the version.

**Comment by benansell** [comment]
@rtfeldman - can this be closed?

**Comment by rtfeldman** [comment]
Yep! Thanks @benansell!
