### ISSUE TITLE
--compiler does not work with absolute path

### ISSUE THREAD

**Issue by RavenDream** [rtfeldman/node-test-runner#338]
using elm-test 0.19.0-rev4 I get the following output when attempting to run with relative and absolute paths.

```
/home/user/src/github.com/elm-coverage/tests/data/simple
[user@work simple]$ elm-test --compiler /home/user/src/github.com/bin/fake-elm                                                                    
Unhandled exception while running the tests: Error: The --compiler option must be given a path to an elm executable.                              
    at Object.<anonymous> (/home/user/.local/lib/node_modules/elm-test/lib/elm-test.js:108:11)                                                    
    at Module._compile (module.js:653:30)
    at Object.Module._extensions..js (module.js:664:10)
    at Module.load (module.js:566:32)
    at tryModuleLoad (module.js:506:12)
    at Function.Module._load (module.js:498:3)
    at Module.require (module.js:597:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/home/user/.local/lib/node_modules/elm-test/bin/elm-test:3:1)                                                          
    at Module._compile (module.js:653:30)
    at Object.Module._extensions..js (module.js:664:10)
    at Module.load (module.js:566:32)
    at tryModuleLoad (module.js:506:12)
    at Function.Module._load (module.js:498:3)
    at Function.Module.runMain (module.js:694:10)
    at startup (bootstrap_node.js:204:16)
    at bootstrap_node.js:625:3
[user@work simple]$ elm-test --compiler ../../../bin/fake-elm

elm-test 0.19.0-rev4
--------------------

Running 1 test. To reproduce these results, run: elm-test --fuzz 100 --seed 227966061569124 /home/user/src/github.com/elm-coverage/tests/data/simple/tests/Example.elm


TEST RUN PASSED

Duration: 164 ms
Passed:   1
Failed:   0

[user@work simple]$ readlink -f ../../../bin/fake-elm
/home/user/src/github.com/elm-coverage/bin/fake-elm
```

**Comment by harrysarson** [comment]
Hi @RavenDream, what does your terminal give you if you run:

```bash
which /home/user/src/github.com/elm-coverage/bin/fake-elm
```

I suspect (and I may be wrong!) that the path you are giving to elm test does not point to an elm executable.

**Comment by zwilias** [comment]
@RavenDream `/home/user/src/github.com/bin/fake-elm` is not `/home/user/src/github.com/elm-coverage/bin/fake-elm`.

**Comment by RavenDream** [comment]
Wow, can hardly believe I missed that.
