### ISSUE TITLE
Newest elm-test crashes with "You are giving module `Main` an argument in JavaScript."

### ISSUE THREAD

**Issue by jaapz** [rtfeldman/node-test-runner#62]
Using latest elm-test runner, the runner crashes with this error:

```bash
$ elm-test TestRunner.elm
Success! Compiled 1 module.
Successfully generated /tmp/elm_test_116719-15843-1kmv9mo.edvilcv7vi.js
undefined:1929
                        throw new Error(
                        ^

Error: You are giving module `Main` an argument in JavaScript.
This module does not take arguments though! You probably need to change the
initialization code to something like `Elm.Main.fullscreen()`
    at init (eval at <anonymous> (/usr/lib/node_modules/elm-test/bin/elm-test:86:37), <anonymous>:1929:10)
    at Object.eval [as callback] (eval at <anonymous> (/usr/lib/node_modules/elm-test/bin/elm-test:86:37), <anonymous>:1973:17)
    at step (eval at <anonymous> (/usr/lib/node_modules/elm-test/bin/elm-test:86:37), <anonymous>:2613:39)
    at Timeout.work [as _onTimeout] (eval at <anonymous> (/usr/lib/node_modules/elm-test/bin/elm-test:86:37), <anonymous>:2671:15)
    at tryOnTimeout (timers.js:232:11)
    at Timer.listOnTimeout (timers.js:202:5)
```

TestRunner.elm looks like this:

```haskell
port module Main exposing (..)

import Test.Runner.Node exposing (run)
import Tests
import Json.Encode exposing (Value)


main : Program Never
main =
    run emit Tests.all


port emit : ( String, Value ) -> Cmd msg
```

```bash
$ elm --version
0.17.1

$ elm-test --version
0.17.3

$ node --version
v6.4.0
```

**Comment by rtfeldman** [comment]
@jaapz It's gotta be `Program Value` now, not `Program Never`.

Not sure how we can easily detect this, but that's the problem. 😄

**Comment by jaapz** [comment]
Jep, that was the problem, thanks!
