### ISSUE TITLE
Error: You are giving module `Main` an argument in JavaScript

### ISSUE THREAD

**Issue by mgold** [rtfeldman/node-test-runner#70]
I'm getting a runtime error. 😞 To reproduce:

```
cd $TMPDIR
git clone git@github.com:mgold/elm-nonempty-list.git
cd elm-nonempty-list
elm-make
```

Result:

```
Starting downloads...

  ● elm-lang/lazy 1.0.0
  ● elm-community/elm-test 2.0.1
  ● mgold/elm-random-pcg 3.0.1
  ● elm-lang/core 4.0.5
  ● elm-community/elm-lazy-list 1.3.0
  ● elm-lang/html 1.1.0
  ● rtfeldman/node-test-runner 1.0.0
  ● elm-community/shrink 1.1.0
  ● elm-lang/virtual-dom 1.1.1

Packages configured successfully!
Success! Compiled 49 modules.                                       
Successfully generated /var/folders/ll/yf9q1nj56sb97s7twbtvl88c0000gn/T/elm_test_11685-7708-2zs4pk.yslkk5ipb9.js
undefined:1929
			throw new Error(
			^

Error: You are giving module `Main` an argument in JavaScript.
This module does not take arguments though! You probably need to change the
initialization code to something like `Elm.Main.fullscreen()`
    at init (eval at <anonymous> (/usr/local/lib/node_modules/elm-test/bin/elm-test:86:37), <anonymous>:1929:10)
    at Object.eval [as callback] (eval at <anonymous> (/usr/local/lib/node_modules/elm-test/bin/elm-test:86:37), <anonymous>:1973:17)
    at step (eval at <anonymous> (/usr/local/lib/node_modules/elm-test/bin/elm-test:86:37), <anonymous>:2613:39)
    at Timeout.work [as _onTimeout] (eval at <anonymous> (/usr/local/lib/node_modules/elm-test/bin/elm-test:86:37), <anonymous>:2671:15)
    at tryOnTimeout (timers.js:232:11)
    at Timer.listOnTimeout (timers.js:202:5)
```

What's going on?

**Comment by rtfeldman** [comment]
@mgold probably you are on an older version of the `elm-test` binary; try `npm install -g elm-test`

**Comment by mgold** [comment]
I checked and just double-checked that. I'm still getting the error.

**Comment by rtfeldman** [comment]
Ah, the mismatch is the other way around - you have the latest `elm-test` binary but are using the older package.

I made a PR to fix it: https://github.com/mgold/elm-nonempty-list/pull/2

<img width="792" alt="screen shot 2016-09-05 at 9 47 04 pm" src="https://cloud.githubusercontent.com/assets/1094080/18261981/507a2b06-73b2-11e6-9da4-24be364594df.png">

**Comment by mgold** [comment]
Oh how funny! Thanks for the PR, will merge when build succeeds. (Why isn't there a GH button for that? GitLab has it...)
